### ISSUE TITLE
Globalize rooms array

### ISSUE THREAD

**Issue by jazmand** [jazmand/jupiters-bounty#30]
Need a way to access the most up-to-date rooms array from multiple scripts. In particular, the array will be updated when rooms are built or removed, so it must be updated and accessed from a shared location.

**Comment by conalli** [comment]
Yeah, I agree. I was thinking that we will probably need to do something similar for the GUI, too.

**Comment by conalli** [comment]
@jazmand added this morning, ref https://github.com/jazmand/jupiters-bounty/commit/211a4db2318df4be74e753ce6c5708310d0e34c2
