### ISSUE TITLE
Make 2x2 rooms impossible to build

### ISSUE THREAD

**Issue by conalli** [jazmand/jupiters-bounty#33]
i think this was mentioned before but due to not being able to place a door in a corner, it is not possible to build a 2x2 room, however 2x2 rooms (cant remember which type) are displayed as blue (buildable)

**Comment by khatakslied** [comment]
Ok. This is being controlled by a roomtype's minimum tiles. Currently 6 is the smallest so 2x3 is the smallest room. But we could add another validation to make sure there are unblocked non-corner tiles.
