### ISSUE TITLE
Add edit rooms icon button

### ISSUE THREAD

**Issue by conalli** [jazmand/jupiters-bounty#67]
- a temporary icon is fine as they will be changed to align with whatever style we decide upon

**Comment by khatakslied** [comment]
I was going to add a button but then I remembered one of you (@conalli @jazmand) suggested adding a clickable 'shape' to the room to be able to select it on clicking. I think that would be a nicer, more intuitive way to select a room. We can change the cursor on hovering and even add a message in the cursor label to make it clear when a click would trigger room selection. And we could do the same with crew. The label could appear after .5 - 1 seconds of hovering so as to prevent things looking too busy. 

What do you think?
